/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx_hal.h"
#include <string.h>

I2C_HandleTypeDef hi2c1;

uint8_t rxBuffer[32];

#define SLAVE_ADDR (0x68 << 1)   // ⚠️ IMPORTANT shift

/* ================= GPIO INIT ================= */
void I2C1_GPIOInit(void)
{
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    GPIO_InitStruct.Pin = GPIO_PIN_6 | GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_OD;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_FAST;
    GPIO_InitStruct.Alternate = GPIO_AF4_I2C1;

    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

/* ================= I2C INIT ================= */
void I2C1_Init(void)
{
    __HAL_RCC_I2C1_CLK_ENABLE();

    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = 100000;
    hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1 = 0x61;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.Ack = I2C_ACK_ENABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;

    HAL_I2C_Init(&hi2c1);
}

/* ================= MAIN ================= */
int main(void)
{
    HAL_Init();

    I2C1_GPIOInit();
    I2C1_Init();

    char msg[] = "Hello ESP32";

    while(1)
    {
        HAL_I2C_Master_Transmit(&hi2c1,
                                SLAVE_ADDR,
                                (uint8_t*)msg,
                                strlen(msg),
                                HAL_MAX_DELAY);

        HAL_Delay(500);

        HAL_I2C_Master_Receive(&hi2c1,
                               SLAVE_ADDR,
                               rxBuffer,
                               11,
                               HAL_MAX_DELAY);

        HAL_Delay(500);
    }
}
